name: Publish compass-web
on:
  workflow_dispatch:
  push:
    branches:
      - compass-web@0.12.2-patches

jobs:
  publish:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: "Use Node.js 20"
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
          registry-url: "https://registry.npmjs.org"

      - name: Install Dependencies
        run: |
          npm run bootstrap-ci
        shell: bash

      - name: Build compass-web
        run: |
          npm run prepublishOnly --workspace=@haohanyang/compass-web
          cp LICENSE packages/compass-web
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: haohanyang-compass-web-0.12.2-patch1.tgz
          path: |
            packages/compass-web/dist
            packages/compass-web/LICENSE
            packages/compass-web/package.json
      - name: Publish compass-web
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish --provenance --access public
        working-directory: ./packages/compass-web
