name: Publish compass-web
on:
  push:
    branches:
      - compass-web@0.12.2-patches

jobs:
  publish:
    if: |
      startsWith(github.event.head_commit.message, '[release]')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup git
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

      - name: "Use Node.js 14"
        uses: actions/setup-node@v3
        with:
          node-version: 20.16.0

      - name: Install npm@10.2.4
        run: npm install -g npm@10.2.4

      - name: Install Dependencies
        run: |
          npm run bootstrap-ci
        shell: bash

      - name: Publish compass-web
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish --provenance --access public
        working-directory: ./packages/compass-web
